apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaeger
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://jaegertracing.github.io/helm-charts'
    chart: jaeger
    targetRevision: 3.3.3
    helm:
      values: |
        provisionDataStore:
          cassandra: false
        allInOne:
          enabled: true
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
              - jaeger.local
            path: /
            pathType: Prefix
        
        agent:
          enabled: false
        collector:
          enabled: false
        query:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true