apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaeger
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://jaegertracing.github.io/helm-charts'
    chart: jaeger
    targetRevision: 3.3.3
    helm:
      values: |
        # 1. 무거운 기본 DB(카산드라) 생성 끄기
        provisionDataStore:
          cassandra: false
        
        storage:
          type: memory
        
        # 2. 가벼운 All-in-One(개발용) 모드 켜기
        allInOne:
          enabled: true
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
              - jaeger.127.0.0.1.nip.io
            path: /
            pathType: Prefix
        
        # 3. 개별 컴포넌트들 끄기 (All-in-One이 다 처리하므로 필요 없음)
        agent:
          enabled: false
        collector:
          enabled: false
        query:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true