apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    chart: mysql
    targetRevision: 10.1.0
    helm:
      values: |
        # 1. Secret 사용
        image:
          registry: docker.io
          repository: bitnamilegacy/mysql
        
        volumePermissions:
          image:
            registry: docker.io
            repository: bitnamilegacy/os-shell
        
        auth:
          existingSecret: "mysql-credentials"
          rootPasswordKey: "mysql-root-password"
          databaseKey: "mysql-database"
          userKey: "mysql-user"
          passwordKey: "mysql-password"

        # 2. 데이터 영속성 설정 (PVC 생성)
        primary:
          persistence:
            enabled: true
            size: 8Gi
          # 서비스 타입을 ClusterIP로 설정 (내부 통신용)
          service:
            type: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: database
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true