apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    chart: mysql
    targetRevision: 14.0.3
    helm:
      values: |
        architecture: standalone
        
        auth:
          existingSecret: "mysql-credentials"
      
          database: "pond"
          username: "pond_user" # (만약 root 외에 별도로 만든 유저가 있다면 주석을 풀고 적어주세요)

        primary:
          persistence:
            enabled: true
            size: 8Gi
          service:
            type: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: database
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true