apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-collector
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://open-telemetry.github.io/opentelemetry-helm-charts'
    chart: opentelemetry-collector
    targetRevision: 0.118.0
    helm:
      values: |
        mode: deployment
        image:
          repository: "otel/opentelemetry-collector-k8s"

        serviceMonitor:
          enabled: true
          extraLabels:
            release: monitoring-stack

        config:
          extensions:
            health_check:
              endpoint: "0.0.0.0:13133"

          receivers:
            otlp:
              protocols:
                grpc:
                  endpoint: 0.0.0.0:4317
                http:
                  endpoint: 0.0.0.0:4318
        
          processors:
            batch: {}
        
          exporters:
            otlp/jaeger:
              endpoint: "jaeger-collector.monitoring.svc.cluster.local:4317"
              tls:
                insecure: true
        
            prometheus:
              endpoint: "0.0.0.0:8889"
        
            debug:
              verbosity: detailed

          service:
            extensions: [health_check]
        
            pipelines:        
              traces:
                receivers: [otlp]
                processors: [batch]
                exporters: [otlp/jaeger, debug]
        
              metrics/forward:
                receivers: [otlp]
                processors: [batch]
                exporters: [prometheus, debug]
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true