apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    chart: redis
    helm:
      values: |
        image:
          registry: docker.io
          repository: bitnamilegacy/redis
        
        volumePermissions:
          image:
            registry: docker.io
            repository: bitnamilegacy/os-shell
        
        architecture: standalone
        
        auth:
          enabled: false

        master:
          persistence:
            enabled: true
            size: 2Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: database
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true