apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBCluster
metadata:
  name: pond-db
  namespace: database
spec:
  crVersion: 1.15.0
  allowUnsafeConfigurations: true
  # 1. 3중화 설정 (High Availability)
  # 노트북 자원이 부족하면 size를 3에서 1로 줄여서 테스트해도 되지만, 공부를 위해 3을 추천합니다!
  pxc:
    size: 2
    image: percona/percona-xtradb-cluster:8.0.35-27.1
    nodeSelector:
      pond-db-eligible: "true"
    resources:
      requests:
        memory: 512Mi
        cpu: 300m
      limits:
        memory: 1Gi
        cpu: 600m
    volumeSpec:
      persistentVolumeClaim:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi
    # 안티 어피니티 (DB들끼리 서로 다른 노드에 찢어놓기)
    affinity:
      antiAffinityTopologyKey: "none"
      advanced:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/component
                      operator: In
                      values:
                        - pond-db
                topologyKey: "kubernetes.io/hostname"

  # 2. 사용자 계정 연동
  # secretsName: mysql-pxc-credentials

  # 3. 프록시 설정 (앱이 DB 주소를 하나만 바라보게 해줌)
  haproxy:
    enabled: true
    size: 2
    image: percona/haproxy:2.8.17
    resources:
      requests:
        cpu: 100m
        memory: 128Mi

  backup:
    image: percona/percona-xtradb-cluster-operator:1.13.0-pxc8.0-backup
    # R2 저장소 설정
    storages:
      r2-storage:
        type: s3
        s3:
          bucket: pond-db-backup  # R2 버킷 이름
          credentialsSecret: pxc-cluster-backup-secret
          region: auto
          endpointUrl: https://d9d59b80a6fa28a1a2461682d11cfa2a.r2.cloudflarestorage.com

    # 자동 백업 스케줄 설정
    schedule:
      - name: "daily-backup"
        # 매일 새벽 3시(한국 시간)에 백업 실행 (Cron 표현식)
        # 쿠버네티스는 기본 UTC 기준이므로, 한국 새벽 3시면 UTC 오후 6시(18:00) 입니다.
        schedule: "0 18 * * *"
        keep: 5  # 최근 5개의 백업 파일만 유지하고 오래된 것은 자동 삭제 (비용 절감)
        storageName: r2-storage