apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBCluster
metadata:
  name: pond-db
  namespace: database
spec:
  crVersion: 1.15.0
  # 1. 3중화 설정 (High Availability)
  # 노트북 자원이 부족하면 size를 3에서 1로 줄여서 테스트해도 되지만, 공부를 위해 3을 추천합니다!
  pxc:
    size: 3
    image: percona/percona-xtradb-cluster:8.0.35-27.1
    nodeSelector:
      role: data-node
    resources:
      requests:
        memory: 512Mi
        cpu: 300m
      limits:
        memory: 1Gi
        cpu: 600m
    volumeSpec:
      persistentVolumeClaim:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi
    # 안티 어피니티 (DB들끼리 서로 다른 노드에 찢어놓기)
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/component
                    operator: In
                    values:
                      - pxc
              topologyKey: "kubernetes.io/hostname"

  # 2. 사용자 계정 연동
  secretsName: mysql-credentials

  # 3. 프록시 설정 (앱이 DB 주소를 하나만 바라보게 해줌)
  haproxy:
    enabled: true
    size: 2
    image: percona/percona-xtradb-cluster-operator:1.15.0-haproxy
    resources:
      requests:
        cpu: 100m
        memory: 128Mi