apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/jshjshjshjsh/pond_k8s_config.git' # 본인의 설정 저장소 주소
    targetRevision: HEAD
    # ✨ 방금 만든 ingress 폴더를 가리키도록 경로를 지정합니다.
    path: ingress
  destination:
    server: https://kubernetes.default.svc
    # Ingress는 default 네임스페이스에 있는 서비스들을 연결해 줍니다.
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true