apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  annotations:
    # Ingress 규칙(ingress-app)보다 먼저 배포되도록 sync-wave를 2로 설정합니다.
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # NGINX Ingress Controller의 공식 Helm 차트 저장소 주소입니다.
    repoURL: 'https://kubernetes.github.io/ingress-nginx'
    chart: ingress-nginx
    targetRevision: 4.10.1 # 안정적인 차트 버전 명시
    helm:
      # Ingress Controller를 위한 추가 설정 값입니다.
      values: |
        controller:
          # 서비스 타입을 LoadBalancer로 설정하여 외부에서 접근할 수 있도록 합니다.
          service:
            type: LoadBalancer
          # IngressClass 리소스를 생성하고, 이름이 'nginx'인 Ingress만 감시하도록 설정합니다.
          ingressClassResource:
            name: nginx
            enabled: true
            default: true
            controllerValue: "k8s.io/ingress-nginx"
  destination:
    server: https://kubernetes.default.svc
    # Ingress Controller는 별도의 네임스페이스에 설치하는 것이 일반적입니다.
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    # 'ingress-nginx' 네임스페이스가 없다면 자동으로 생성합니다.
    - CreateNamespace=true