apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pond-front
  namespace: argocd
  # ✨ finalizer를 추가하면 Argo CD UI에서 앱을 삭제할 때 관련 리소스도 함께 정리됩니다.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # Argo CD가 바라볼 Git 저장소 주소입니다.
    repoURL: 'https://github.com/jshjshjshjsh/pond_k8s_config.git' # 본인의 설정 저장소 주소
    targetRevision: HEAD
    # 저장소 내에서 pond-front Helm 차트가 있는 폴더 경로입니다.
    path: pond-front
    helm:
      # pond-front/values.yaml 파일을 사용하도록 지정합니다.
      valueFiles:
      - values.yaml
  destination:
    # 이 애플리케이션이 배포될 Kubernetes 클러스터 주소입니다.
    server: https://kubernetes.default.svc
    # 배포될 네임스페이스를 지정합니다.
    namespace: default
  syncPolicy:
    automated:
      # prune: true -> Git에서 사라진 내용은 클러스터에서도 자동으로 삭제합니다.
      prune: true
      # selfHeal: true -> 클러스터의 상태가 Git과 달라지면 자동으로 Git의 상태로 복구합니다.
      selfHeal: true
    # ✨ syncOptions를 통해 배포되지 않은 리소스도 자동으로 생성하도록 합니다.
    syncOptions:
    - CreateNamespace=true