apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base
  namespace: argocd
  annotations:
    # 뇌(Istiod)보다 뼈대(Base/CRD)가 먼저 설치되도록 순서를 -2로 당깁니다.
    argocd.argoproj.io/sync-wave: "-2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: base
    targetRevision: 1.22.0 # 최신 안정 버전
  destination:
    server: https://kubernetes.default.svc
    # Istio는 반드시 istio-system 이라는 전용 네임스페이스를 씁니다.
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true