apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiali
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # Kiali 공식 헬름 차트 저장소
    repoURL: 'https://kiali.org/helm-charts'
    chart: kiali-server
    targetRevision: 1.84.0 # 최신 안정 버전
    helm:
      values: |
        auth:
          # 로컬 테스트용이므로 번거로운 로그인 과정을 끕니다. (운영에서는 토큰/OIDC 등을 사용)
          strategy: anonymous
        
        server:
          port: 20001
          web_root: /
        
        ingress:
          enabled: true
          class_name: "nginx"
          hosts:
            - kiali.theponds.work
        
        # 기존에 설치된 Prometheus와 연동하여 메트릭을 가져옴
        external_services:
          prometheus:
            url: "http://monitoring-stack-kube-prom-prometheus.monitoring.svc.cluster.local:9090"
        
          # (선택) 추후 Jaeger 분산 추적과 연동할 때 씁니다.
          tracing:
            enabled: true
            in_cluster_url: "http://jaeger-query.monitoring.svc.cluster.local:16685"
            use_grpc: false

  destination:
    server: https://kubernetes.default.svc
    # Kiali는 istio-system 네임스페이스에 설치
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true