apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/jshjshjshjsh/pond_k8s_config.git'
    targetRevision: HEAD
    path: secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: pond
  syncPolicy:
    automated:
      prune: true
      selfHeal: true