---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-credentials
  namespace: default
spec:
  encryptedData:
    password: AgBJOGi/Mov8DiN98PbaV0W52UdEgZ9nY8hTe8fwz8fgMhRz2o65FCzG0gxFiFBBTSHmHVj+RYDirrm01lUDF5kL/Fd+5xEMrTdQyw69VoO/2lWWSI9ZoXIPSxaspJ3/iDDm/gyuoIzNTHItGlr/ikUVGxy+D6apAjN9OldOIJhtgnNSTYIL+Eh7HtvlqrNNtxKAicZtMUhbu7Rj2DpZs7WS+a4etJJqwxDLL7+QAIAbIlw7r9ew7lTqX2kOQDzoOmsM7ojvjYXFjFTBf1tmOwxqswXH1YuIT179tmgcNdYm9JmwxwvpZjrw8KhZV5ggaeCM55dWtfk1r4Dy5yebcGiQHr14nBewqhWq/6hgYm4CRE4iUQgWd4dMbImocdkvNoBz1H3Ugj4s/5Mchl5pYhuh8nJ1vlIU4lW1I+unyVEcsUvmArFfIosQVSVXw3LZW/zO/SkOJlDniN4WtoUAWb8r4r2l0PTBi04F8i2XTGA+VllSAoQHQ/4rgSVr2RlbMVNnI95zqkvIya5Y/FnaOrVmn/Aea7Dbqxo3rpQkRk2JaIrWzHMxUKM7a0VcCvF4O+DeMX4ui2XDBKn1lW5+pM++LxxO0wsm3kt4vqTr++sva9AGjiDB54A6PVVTC4X+1W2bmcLUvCdKvlKR4w8SiJZ4yCxDoR0lloYdV4iiOL+GPsgQnWr1tV3jjxjIehcHQ0+qbCfNe52jjNcGG+Pijw==
    username: AgBxag4Sju7tnOgu4Bv0b5PjRWIGYKjHYHQuH/FwVuSoITm+8KDscUXC8r97/mxnGCAAIZTb3ekqMwyBOGfCSoIFNyW4YMAWKAq2F8YNUw/ueqZn625Mr1cPOYMj8MjYQBWgYRalinjsglvNNTvgvk9Sl+kiK9WmoPeXyNKRWx6pXDyFffQBaCZ14f/fzlZJETzWGuRZ8mNHF2nGlT2mObpykI7+UE1yXgVy2z6dNsa7PQImydIu0qtt9d/VLlq8P0KeiJtXoX23EdH7Wt6cBje1gkbkFnjG80hBkPXVDxiNCgPJ3I1W+BanabCW96nToRUwlhQLrbZ5XOHNz4grZShE+xWjOfVCzdBZbtoQ8POk3sM1ZEbXqrMBhfIYvwT5YOcE/pHJyXhsHU/oC2bkjtI69jITCZCgogp419ZMilb65VWfJK0wO+zaQ7RDOyfBn5pUYrsDVQ/mJ85XFpwTYRw1fjSdy1ivsJWtDKcTTOXh0mIhNZYNPgHOcebBLOk5AYtLcXpG6527ahlXuWCpCog5n5nBbVOiuEFhu+0wlunHn8Zyn7uM6m9faX/Qn03RLPInJD8+kJ9J+9m/U+vtoiJ5oMh2zE74dOkBvd0k4GXGMf80FLT5Jzln4dP6y2kXpTTkfJe5xve+pkxd7mAvry19VaAKyEUjWk+ljxtmy/sc6clQi3IB/iCfBBBS+KPT2maDrWeDpgfWDaY=
  template:
    metadata:
      creationTimestamp: null
      name: db-credentials
      namespace: default
    type: Opaque
