# secrets/eso-pond-back-secrets.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pond-back-external-secret
  namespace: pond
spec:
  refreshInterval: "1m" # 빠른 테스트를 위해 1분마다 갱신 확인
  secretStoreRef:
    name: vault-backend
    kind: SecretStore

  target:
    name: pond-back-secrets

  data:
    - secretKey: jwt-secret
      remoteRef:
        key: pond-back-secrets
        property: jwt-secret

    - secretKey: gemini-api-secret
      remoteRef:
        key: pond-back-secrets
        property: gemini-api-secret